language: ruby
sudo: false
script: 'script/cibuild'
cache: bundler

before_install:
  - gem install bundler -v 2.1.0

env:
  matrix:
    - SUITE=mysql
    - SUITE=pg
    - SUITE=sqlite3
    - SUITE=rubocop
    - SUITE=setup

rvm:
  - 2.5.7
  - 2.6.5

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.6.5
  include:
    - rvm: 2.6.5
      env: SUITE=sqlite3

notifications:
  email: false

services:
  - redis
  - mysql
  - postgresql

bundler_args: --without deploy production debug --jobs 3 --retry 3
